### ISSUE TITLE
Compile Instructions?

### ISSUE THREAD

**Issue by ghost** [Earthcomputer/EnchantmentCracking#1]
How do you build this project into a .litemod file? I downloaded it onto my Linux laptop and typed in ./build.gradle but it said "bash: ./build.gradle: Permission denied". So how do you run it? Or am I suppoed to run something else? I have never really worked with LiteLoader, so I might be missing something important.

**Comment by rolbk** [comment]
To make it runnable you'd use _chmod +x ./filename_, but since it is a Gradle Build Script, AFAIK it isn't runnable by bash in the first place. Use _./gradlew build instead_.

**Comment by ghost** [comment]
Thanks a lot!
