### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Vonr** [Earthcomputer/EnchantmentCracking#2]
https://ghostbin.com/paste/pt2xu
Using latest snapshot of liteloader for 1.12 (not 1.12.2)

**Comment by rolbk** [comment]
Same mc, same liteloader, same issue, same crashlog
So we're two...

**Comment by Ilomantis** [comment]
Same crash on my end.

**Comment by rolbk** [comment]
If you want to you can manually remove the EntityMooshroom from the mixin - a bit hacky but works...

**Comment by Ilomantis** [comment]
Yup, that seemed to fix it.

**Comment by rolbk** [comment]
Just make sure that you don’t actually hit a Moosh while Enchanting ;P

**Comment by Earthcomputer** [comment]
Sorry for late reply, but just got back to this project again. What other mods did you have installed at the time of the crash? I know it doesn't look like it from the crash report, but was Forge installed?

**Comment by rolbk** [comment]
None

**Comment by Earthcomputer** [comment]
What version of liteloader were you using?

**Comment by Ilomantis** [comment]
According to one of my log files, the exact Liteloader version was `1.12-SNAPSHOT-r4CA9C4E-b9-9`. 

However it doesn't seem like the [latest](http://jenkins.liteloader.com/view/1.12/) Liteloader 1.12 snapshot has changed in about a year, and that was the one I downloaded - so you could just grab that one.

**Comment by Earthcomputer** [comment]
To diagnose this further, could you send me a copy of the compiled enchantment_cracking litemod file you used?

**Comment by Ilomantis** [comment]
Here is the one I compiled last month with the EntityMooshroom removed from the mixin
[enchantment_cracking.zip](https://github.com/Earthcomputer/EnchantmentCracking/files/2344284/enchantment_cracking.zip)

**Comment by Earthcomputer** [comment]
Can you give the broken version, with the EntityMooshroom included?

**Comment by Ilomantis** [comment]
Yep, here.
[enchantment_cracking_mooshroom.zip](https://github.com/Earthcomputer/EnchantmentCracking/files/2344345/enchantment_cracking_mooshroom.zip)

**Comment by Earthcomputer** [comment]
My `MixinEntityMooshroom.class` only contains two methods:
```
Compiled from "MixinEntityMooshroom.java"
public abstract class net.earthcomputer.enchcrack.mixin.MixinEntityMooshroom extends zv {
  public net.earthcomputer.enchcrack.mixin.MixinEntityMooshroom(ams);
  public void onProcessInteract(aeb, tz, org.spongepowered.asm.mixin.injection.callback.CallbackInfoReturnable<java.lang.Boolean>);
}
```
While yours contains three:
```
Compiled from "MixinEntityMooshroom.java"
public abstract class net.earthcomputer.enchcrack.mixin.MixinEntityMooshroom extends zv {
  public net.earthcomputer.enchcrack.mixin.MixinEntityMooshroom(ams);
  public void onProcessInteract(aeb, tz, org.spongepowered.asm.mixin.injection.callback.CallbackInfoReturnable<java.lang.Boolean>);
  public vb a(vb);
}
```
The extra method in your version contains the synthetic flag, which means it is compiler generated. I think this method is derived from `EntityAnimal.createChild`.
